package finance.uc_project.enums;

public enum  TypeChef {
    UC,
    DG,
    CELLULES,
    CIRCONSCRIPTION_FINANCIERES,
    DIRECTEURS_PRMP,
    SERVICES_CENTRAUX_DIRECTION,
    SERVICES_REGIONAUX_BUDGET,
    SERVICES_REGIONAUX_SOLDE_PENSIONS,
    SERVICES_RATTACHES
}
